### ISSUE TITLE
Add URL support

### ISSUE THREAD

**Issue by jurassicplayer** [jurassicplayer/rhythmbox-radio-record#3]
Grabbing the URI from Rhythmbox gives whatever URI was given to Rhythmbox when the radio station was added, not the actual stream.

Just make sure it isn't a playlist file somehow and then send to streamripper.

**Comment by fossfreedom** [comment]
just a quick one - my plugin here records radiostreams via streamripper - maybe there is some code hints here you could use for your plugin.

Hope this helps - https://github.com/fossfreedom/radio-browser

specifically - https://github.com/fossfreedom/radio-browser/blob/83ff85613eceb2fd2fb918b46af3a46a1e2aa72b/record_process.py

**Comment by jurassicplayer** [comment]
Thanks. I have been using a variety of plugins to figure out what to do (including a couple of yours). 

URL support should be working for any mp3 stream, but I need to check out what the other content-types return (aac, ogg, ra, any other streaming format commonly used) and add them to the if statement.

**Comment by jurassicplayer** [comment]
Hopefully recursive playlist support will cover everything since it gets mp3/aac/ogg or defaults to whatever was passed. If the url is bad, then I'll just crop it up to user error and leave it there.
